sudo: false
language: node_js
node_js:  
  - node
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm run test

#after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"